[colors]
background = "#1E1C1A"
foreground = "#DCD8D4"
cursor_bg = "#DCD8D4"
cursor_fg = "#1E1C1A"
cursor_border = "#DCD8D4"
selection_fg = "#DCD8D4"
selection_bg = "#2E4C7A"
scrollbar_thumb = "#161412"
split = "#3E3A38"

ansi = ["#161412", "#FF5C5C", "#3DDC84", "#FEA413", "#5C8CFF", "#9B6ABF", "#3A9BA5", "#A5A8AF"]
brights = ["#787068", "#E85B61", "#6BCF70", "#FFBD4A", "#6B8AD8", "#BB8EDA", "#5CBDC7", "#DCD8D4"]

[colors.tab_bar]
background = "#161412"

[colors.tab_bar.active_tab]
bg_color = "#23438E"
fg_color = "#DCD8D4"

[colors.tab_bar.inactive_tab]
bg_color = "#1E1C1A"
fg_color = "#A5A8AF"

[colors.tab_bar.new_tab]
bg_color = "#1E1C1A"
fg_color = "#A5A8AF"

[metadata]
name = "nepes-dark"
author = "kaypark"
